name: Update Lambda Function

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to ECR"]
    types:
      - completed

jobs:
  update-lambda:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda function with new container image
        run: |
          aws lambda update-function-code \
            --function-name my_lambda_function \
            --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/lambda-microservice:latest
